Test observability
browserstack/browserstack-examples-nightwatchjs pull request #23
Opened 2023-09-12 08:59 UTC by Yatin2108

Test observability added

2023-09-12 11:05 UTC, princebaretto99 requested changes
Do we need the Design.MD file?

2023-09-13 11:42 UTC, princebaretto99 approved these changes, later dismissed

2023-09-13 11:46 UTC, samirans89 commented on package.json
> +		"@nightwatch/browserstack": "^0.2.1",
why woudn't we use the latest version? https://www.npmjs.com/package/@nightwatch/browserstack/v/3.1.1

2023-09-13 11:48 UTC, samirans89 commented on package.json
>  		"browserstack-local": "1.4.8",
do we need this explicitly?

`@nightwatch/browserstack` already includes browserstack-local

2023-09-13 11:48 UTC, samirans89 commented on package.json
>  		"chromedriver": "^90.0.0",
can we change this to latest chrome, if being used?

2023-09-13 11:49 UTC, samirans89 commented on package.json
> +		"nightwatch": "^2.6.21",
latest version: 3.1.3

2023-09-14 11:43 UTC, samirans89 approved these changes

2023-09-20 14:10 UTC, merged