Secondary Review
browserstack/browserstack-examples-nightwatchjs pull request #3
Opened 2021-03-31 13:05 UTC by RathilVasani

Primary Review is Complete , please proceed for Secondary Review

2021-03-31 17:17 UTC, samiran-bs commented on src/tests/suites/product/index.test.js
> +			.click("xpath", "//span[contains(text(), 'Apple')]")
input[value='Apple'] + span

2021-03-31 17:17 UTC, samiran-bs commented on src/tests/suites/product/index.test.js
> +			.click("xpath", "//span[contains(text(), 'Samsung')]");
input[value='Samsung'] + span

2021-03-31 17:22 UTC, samiran-bs commented on src/tests/suites/product/index.test.js
> +			.waitForElementPresent("xpath", "//*[@class = 'shelf-item'][1]")
css: div.shelf-container-header + div.shelf-item

2021-03-31 17:31 UTC, samiran-bs commented on src/tests/suites/product/index.test.js
> +				"/html/body/div/div/div/main/div[2]/div[2]/div[3]/div[1]/b",
remove xpath.
possible css alternative
div.shelf-item__price > div.val > b
do a getText for this element.

2021-03-31 17:32 UTC, samiran-bs commented on src/tests/suites/product/index.test.js
> +		done();
repeated code. please add reusable function.

2021-03-31 17:33 UTC, samiran-bs commented on src/tests/suites/user/index.test.js
> +			.pause(1000)
can we perform page title or some other field assertion which does not exist on the prev page?

2021-03-31 17:33 UTC, samiran-bs commented on src/tests/suites/user/index.test.js
> +			.pause(1000)
can we perform page title or some other field assertion which does not exist on the prev page?

2021-03-31 17:33 UTC, samiran-bs commented on src/tests/suites/user/index.test.js
> +			.pause(1000)
can we perform page title or some other field assertion which does not exist on the prev page?

2021-03-31 17:36 UTC, samiran-bs commented on src/tests/suites/user/index.test.js
> +			.click("xpath", "//p[text() = 'iPhone 12']/../div/button")
change without xpath.

2021-03-31 17:37 UTC, samiran-bs commented on src/tests/suites/user/index.test.js
> +			.pause(1000)
can we perform page title or some other field assertion which does not exist on the prev page?

2021-03-31 17:37 UTC, samiran-bs commented on src/tests/suites/user/index.test.js
> +		done();
reusable code.

2021-03-31 17:38 UTC, samiran-bs commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
is yarn.lock required to be checked-in ... isn't is auto generated?

2021-03-31 20:29 UTC, NightWing1998 commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
yarn.lock is a peer dependency file like package-lock.json
We can omit this but there could be a good chance that in future some dependency change functionality and our tests will break

2021-04-01 15:12 UTC, samiran-bs requested changes

2021-04-08 17:45 UTC, samiran-bs requested changes

2021-04-08 17:45 UTC, samiran-bs commented on docker-compose.yml
> +version: "3"
update the docker-compose.yml file here using the Selenium 3.14 version which is working for TestNg.
and create a PR here to update this file too.

https://github.com/browserstack/browserstack-examples-reusable-artifacts/blob/main/templates/docker/selenium/docker-compose.yml

2021-04-22 15:39 UTC, samiran-bs approved these changes

2021-04-22 15:41 UTC, merged